#!/usr/bin/python

import sys

sys.path = ["/home/walmis/Desktop/trunk/common/"] + sys.path

import gtk

from blueman.constants import *
from blueman.Gui.manager.manager_device_list import manager_device_list
from blueman.Gui.manager.manager_toolbar import manager_toolbar





class blueman:

	def __init__(self):
		#set icon path
		ic = gtk.icon_theme_get_default()
		ic.prepend_search_path(ICON_PATH)
		ic.prepend_search_path(ICON_PATH + "/devices")
		ic.prepend_search_path(ICON_PATH + "/signal")
		
		self.Builder = gtk.Builder()
		self.Builder.add_from_file(UI_PATH +"/manager-main.ui")

		window = self.Builder.get_object("window")
		sw = self.Builder.get_object("scrollview")
		
		self.List = manager_device_list()
		self.List.show()
		sw.add(self.List)
		
		
		self.Toolbar = manager_toolbar(self)
		
		
		
		self.List.DisplayKnownDevices()
		window.show()
		gtk.main()
		
	def add_device(self, device):
		pass
		
			
	def remove_device(self, device):
		pass
		
	def inquiry(self):
		pass
		
	def setup(self, device):
		pass
		
	def bond(self, device):
		pass
		
	def toggle_trust(self, device):
		pass

		



blueman()
