#!/usr/bin/python

import sys

sys.path = ["/home/walmis/Desktop/trunk/common/"] + sys.path

import gtk

from blueman.constants import *
from blueman.Gui.main_device_list import main_device_list





class blueman:

	def __init__(self):
		#set icon path
		ic = gtk.icon_theme_get_default()
		ic.prepend_search_path(ICON_PATH)
		ic.prepend_search_path(ICON_PATH + "/devices")
		ic.prepend_search_path(ICON_PATH + "/signal")
		
		self.Builder = gtk.Builder()
		self.Builder.add_from_file(UI_PATH +"/manager-main.ui")

		window = self.Builder.get_object("window")
		sw = self.Builder.get_object("scrollview")
		
		self.List = main_device_list()
		self.List.show()
		sw.add(self.List)
		
		self.List.DisplayKnownDevices()
		
		window.show()
		gtk.main()
		



blueman()
