.TH BLUEMAN-ASSISTANT 1 LOCAL

.SH NAME

blueman-assistant - application for configuring and pairing bluetooth devices

.SH SYNOPSIS

.B blueman-assistant [options]

.SH DESCRIPTION

blueman-assistant configures specified device, if there is no device specified, it will display a dialog to choose from.

.SH OPTIONS
.IP --device=ADDRESS
Address of the device to configure

.SH AUTHOR

Valmantas Paliksa
