.TH BLUEMAN-BROWSE 1 LOCAL

.SH NAME

blueman-browse - Helper application for launching an obex browser

.SH SYNOPSIS

.B blueman-browse [options]

.SH DESCRIPTION

blueman-browse Launches an obex browser for specified device, if there is no device specified, it will display a dialog to choose from.

.SH OPTIONS
.IP --device=ADDRESS
Address of the device to browse


.SH AUTHOR

Valmantas Paliksa
