.TH BLUEMAN-SENDTO 1 LOCAL

.SH NAME

blueman-sendto - application for sending files to bluetooth devices

.SH SYNOPSIS

.B blueman-sendto [options]

.SH DESCRIPTION

blueman-sendto sends files to specified device, if there is no device specified, it will display a dialog to choose from all known devices.

.SH OPTIONS
.IP --device=ADDRESS
Address of the device to send to


.SH AUTHOR

Valmantas Paliksa
