install:
	install org.blueman.Mechanism.conf /etc/dbus-1/system.d
	install org.blueman.Mechanism.service /usr/share/dbus-1/system-services
	install org.blueman.policy /usr/share/PolicyKit/policy
	install ../../apps/blueman-mechanism /usr/lib/blueman
