#!/usr/bin/python

import json
import os
import signal
import subprocess
import time
from threading import Thread, Lock
import urllib2
from blueman.Constants import VERSION
from blueman.Functions import get_lockfile, get_pid, is_running

for program in 'adapters', 'applet', 'manager', 'services':
    name = 'blueman-' + program
    lockfile = get_lockfile(name)

    if os.path.exists(lockfile):
        pid = get_pid(lockfile)
        if pid and is_running(name, pid):
            print('Terminating ' + name)
            os.kill(pid, signal.SIGTERM)

applet = subprocess.Popen(['blueman-applet'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

log = ''
actions = []
lines = 0
lock = Lock()


def copy_output():
    global lines, log
    for line in iter(applet.stdout.readline, b''):
        lock.acquire()
        lines += 1
        log += line
        lock.release()

t = Thread(target=copy_output)
t.daemon = True
t.start()

while True:
    action = raw_input('Describe your next action (keep empty if done): ')
    if not action:
        break
    lock.acquire()
    lines += 1
    log += "DEBUG ACTION: " + action + "\n"
    lock.release()
    actions.append((lines, action))
    print('Perform the described action')
    time.sleep(5)

lock.acquire()

data = json.dumps({'files': {'log': {'content': log}}})

url = json.loads(urllib2.urlopen('https://api.github.com/gists', data).read())['html_url']

print("")
print("=====================================")
print("")
print("Use this data in your report:")
print("")
print("=====================================")
print("")
print("blueman: " + VERSION)
print("BlueZ: " + subprocess.Popen(['/usr/sbin/bluetoothd', '-v'], stdout=subprocess.PIPE).stdout.read()[:-1])
print("Distribution: ")
print("Desktop: " + os.environ.get('XDG_CURRENT_DESKTOP'))
print("")
for line, action in actions:
    print(url + '#file-log-L' + str(line) + " " + action)
