name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 120 -t py38 -t py39 -t py310 -t py311 -t py312"
          src: "./blueman/"
